# Generated by Django 2.2.16 on 2023-03-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_auto_20230306_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug тега"),
        ),
    ]
