# Generated by Django 2.2.16 on 2023-03-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_auto_20230306_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название тeга"
            ),
        ),
    ]
