# Generated by Django 2.2.16 on 2023-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_auto_20230306_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(max_length=256, verbose_name="Единица измерения"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                help_text="Введите название ингридиента",
                max_length=70,
                verbose_name="Название ингридиента",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                help_text="Напишите название рецепта",
                max_length=70,
                verbose_name="Название рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.TextField(
                help_text="Напишите описание рецепта",
                max_length=5000,
                verbose_name="Описание рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=70, unique=True, verbose_name="Название тeга"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=64, unique=True, verbose_name="Slug тега"
            ),
        ),
    ]
