# Generated by Django 4.1.7 on 2023-03-13 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_auto_20230307_0818"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("id",),
                "verbose_name": "Ингридиент",
                "verbose_name_plural": "Ингридиенты",
            },
        ),
    ]
