# Generated by Django 2.2.16 on 2023-03-13 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_ingredient_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amountingredient",
            name="ingredients",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to="recipes.Ingredient",
                verbose_name="Ингредиенты в рецептах",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="is_in_shopping_cart",
                to="recipes.Recipe",
                verbose_name="Рецепты в корзине",
            ),
        ),
        migrations.AlterField(
            model_name="favorit",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="is_favorites",
                to="recipes.Recipe",
                verbose_name="Избранные рецепты",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                help_text="Добавьте картинку",
                upload_to="recipe_images/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.AmountIngredient",
                to="recipes.Ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
    ]
