# Generated by Django 2.2.16 on 2023-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_auto_20230315_1453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                help_text="Добавьте изображение",
                upload_to="recipes/images/",
                verbose_name="Картинка",
            ),
        ),
    ]
