# Generated by Django 2.2.16 on 2023-03-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_auto_20230315_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.Tag", verbose_name="Тег"
            ),
        ),
    ]
