# Generated by Django 2.2.16 on 2023-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(help_text="Введите ваш email", max_length=256),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                help_text="Введите ваше имя",
                max_length=70,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                help_text="Введите вашу фамилию",
                max_length=70,
                verbose_name="Фамилия пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                help_text="Введите ваш логин",
                max_length=70,
                unique=True,
                verbose_name="Логин пользователя",
            ),
        ),
    ]
