# Generated by Django 2.2.16 on 2023-03-07 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20230307_0818"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Введите ваш email",
                max_length=256,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
