# Generated by Django 2.2.16 on 2023-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_auto_20230308_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активирован"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                help_text="Укажите пароль", max_length=128, verbose_name="Пароль"
            ),
        ),
    ]
