# Generated by Django 2.2.16 on 2023-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20230308_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
