# Generated by Django 2.2.16 on 2023-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_auto_20230308_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Статус активирован"),
        ),
    ]
