name: Foodgram-app workflow 

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        # обновление pip и зависимостей
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        cd backend/
        pip install -r requirements.txt 

  copy_files_to_server:
    name: Copy infra and docs
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Create projects directory
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: cd projects && mkdir -p foodgram && mkdir -p foodgram/docs

    - name: Copy infra files
      uses: garygrossgarten/github-action-scp@release
      with:
          local: infra/
          remote: /${{ secrets.USERNAME }}/projects/foodgram/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}

    - name: Copy docs
      uses: garygrossgarten/github-action-scp@release
      with:
          local: docs
          remote: /${{ secrets.USERNAME }}/projects/foodgram/docs/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}

  build_and_push_backend_to_docker_hub:
      name: Push backend image to Docker Hub
      runs-on: ubuntu-latest
      needs: tests

      steps:
        - name: Check out the repo
          # Проверка доступности репозитория Docker Hub для workflow
          uses: actions/checkout@v2 
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1 
        - name: Login to Docker 
          # Запуск скрипта авторизации на Docker Hub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USER }} 
            password: ${{ secrets.DOCKER_PASS }}
        - name: Push to Docker Hub
          uses: docker/build-push-action@v2 
          with:
            push: true
            tags: msk357/foodgram_backend:latest
            file: backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_backend_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        local: docs
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          run: scp -r /Users/msk3571/Dev/final/foodgram-project-react/docs msk357@158.160.35.92:/home/msk357

